### PR TITLE
export rds too

### PR DESCRIPTION
**Pull request by daaronr**

### CODE REVIEW

**Comment by daaronr** [comment]
minor update

**Comment by TWJolly** [comment]
@daaronr I've not saved rds files before - what is the advantage?

There's a load statement that uses an absolute path from your PC in  .Rapp.history in this pull. Not sure what is happening there - do you know?

**Comment by daaronr** [comment]
> @daaronr I've not saved rds files before - what is the advantage?
> 
Rds: I was thinking about preserving the data structures (factor formats etc). Also putting the csv files together didn't work for me at first but I guess that's fixed now. 

> There's a load statement that uses an absolute path from your PC in .Rapp.history in this pull. Not sure what is happening there - do you know?
> 

That should be removed I think.

**Comment by daaronr** [comment]
@TWJolly I was having some trouble with the files created from putting the csv's together in combine_available_data.R containing a lot of strange stuff (that work is on Dropbox, although maybe it's easier to collaborate if we move it to Github?). I had thought the error might have come from issues with bringing it in and out of csv format. Rds ("write_rds") would seem to be the way of saving in native R format, preserving data structures, column names, features etc. 

However, it looks like we don't really do anything in terms of defining data structures in the Fundraising_data_pull files anyways, so maybe it doesn't matter?

**Pull request merged**
